// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Gossamer — Android JVM-shim generator
//
// Emits the JVM-side component shims and a manifest skeleton into the
// marked-generated tree `generated/android/`. This is the tooling that
// satisfies the estate rule "any unavoidable JVM-bytecode shim must be
// GENERATED by gossamer's own tooling, not authored by hand and not pushed onto
// downstream apps." The shim SOURCES live as `templates/*.java.tmpl` (gossamer
// tooling inputs, deliberately not `*.java`); this generator stamps the
// do-not-edit banner and writes real `.java` next to a per-app manifest.
//
// Run from the repo root (see `just android-gen`):
//   zig run tools/android-codegen/codegen.zig -- [package] [label] [launcherActivity] [widgetInfoRes]
//
// The five component shims are app-agnostic and emitted verbatim. Only the
// manifest is parameterised (package / label / launcher activity / widget-info
// resource), because that is the one artifact that legitimately varies per app.

const std = @import("std");

const banner_java =
    \\// SPDX-License-Identifier: MPL-2.0
    \\// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
    \\//
    \\// GENERATED by tools/android-codegen — DO NOT EDIT.
    \\// Regenerate with: just android-gen
    \\//
    \\
;

const banner_xml =
    \\<?xml version="1.0" encoding="utf-8"?>
    \\<!--
    \\  SPDX-License-Identifier: MPL-2.0
    \\  GENERATED by tools/android-codegen — DO NOT EDIT. Regenerate: just android-gen.
    \\  Copy into your app module and fill any remaining app-specific entries.
    \\-->
    \\
;

const Config = struct {
    package: []const u8 = "com.example.app",
    label: []const u8 = "Gossamer App",
    launcher_activity: []const u8 = ".MainActivity",
    widget_info_resource: []const u8 = "@xml/gossamer_widget_info",
};

const out_dir = "generated/android";
const out_java_dir = out_dir ++ "/java/io/gossamer";

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const args = try std.process.argsAlloc(alloc);
    defer std.process.argsFree(alloc, args);

    var cfg = Config{};
    if (args.len > 1) cfg.package = args[1];
    if (args.len > 2) cfg.label = args[2];
    if (args.len > 3) cfg.launcher_activity = args[3];
    if (args.len > 4) cfg.widget_info_resource = args[4];

    try std.fs.cwd().makePath(out_java_dir);

    try emitJava(alloc, "GossamerActivity.java", @embedFile("templates/GossamerActivity.java.tmpl"));
    try emitJava(alloc, "GossamerBridge.java", @embedFile("templates/GossamerBridge.java.tmpl"));
    try emitJava(alloc, "GossamerService.java", @embedFile("templates/GossamerService.java.tmpl"));
    try emitJava(alloc, "GossamerReceiver.java", @embedFile("templates/GossamerReceiver.java.tmpl"));
    try emitJava(alloc, "GossamerWidget.java", @embedFile("templates/GossamerWidget.java.tmpl"));

    try emitManifest(alloc, cfg);

    std.debug.print("gossamer android-codegen: wrote shims + manifest to {s}/\n", .{out_dir});
}

/// Write a component shim: banner + verbatim template body.
fn emitJava(alloc: std.mem.Allocator, name: []const u8, body: []const u8) !void {
    const path = try std.fs.path.join(alloc, &.{ out_java_dir, name });
    defer alloc.free(path);
    const contents = try std.fmt.allocPrint(alloc, "{s}{s}", .{ banner_java, body });
    defer alloc.free(contents);
    try writeFile(path, contents);
}

/// Write the manifest skeleton with the four placeholders substituted.
fn emitManifest(alloc: std.mem.Allocator, cfg: Config) !void {
    const tmpl = @embedFile("templates/AndroidManifest.xml.tmpl");
    // The template starts with its own <?xml?> line; drop it so the banner's
    // <?xml?> is the sole prolog.
    const body = stripXmlProlog(tmpl);

    var step1 = try std.mem.replaceOwned(u8, alloc, body, "{{APP_PACKAGE}}", cfg.package);
    defer alloc.free(step1);
    var step2 = try std.mem.replaceOwned(u8, alloc, step1, "{{APP_LABEL}}", cfg.label);
    defer alloc.free(step2);
    var step3 = try std.mem.replaceOwned(u8, alloc, step2, "{{LAUNCHER_ACTIVITY}}", cfg.launcher_activity);
    defer alloc.free(step3);
    const step4 = try std.mem.replaceOwned(u8, alloc, step3, "{{WIDGET_INFO_RESOURCE}}", cfg.widget_info_resource);
    defer alloc.free(step4);

    const contents = try std.fmt.allocPrint(alloc, "{s}{s}", .{ banner_xml, step4 });
    defer alloc.free(contents);

    const path = out_dir ++ "/AndroidManifest.template.xml";
    try writeFile(path, contents);
}

fn stripXmlProlog(text: []const u8) []const u8 {
    if (std.mem.indexOf(u8, text, "?>")) |end| {
        var i = end + 2;
        while (i < text.len and (text[i] == '\n' or text[i] == '\r')) : (i += 1) {}
        return text[i..];
    }
    return text;
}

fn writeFile(path: []const u8, contents: []const u8) !void {
    var file = try std.fs.cwd().createFile(path, .{ .truncate = true });
    defer file.close();
    try file.writeAll(contents);
}
