# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
# This workflow is managed by gh actions-lock.
name: Governance

on:
  merge_group:
    types: [checks_requested]
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  governance:
    uses: hyperpolymath/standards/.github/workflows/governance-reusable.yml@7b05a32346a40789271f401afbbb7fb3310b281f
